//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlloK8.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class T {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal T() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlloK8.Common.T", typeof(T).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за акаунта.
        /// </summary>
        public static string AccountDetailsText {
            get {
                return ResourceManager.GetString("AccountDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави нова задача.
        /// </summary>
        public static string AddNewTaskInputLabel {
            get {
                return ResourceManager.GetString("AddNewTaskInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави в проекта.
        /// </summary>
        public static string AddToProjectButtonText {
            get {
                return ResourceManager.GetString("AddToProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при премахването на потребител..
        /// </summary>
        public static string AnErrorOccuredWhileRemovingUserFromProjectErrorMessageText {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhileRemovingUserFromProjectErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговорни.
        /// </summary>
        public static string AssigneesColumnTitlePDFText {
            get {
                return ResourceManager.GetString("AssigneesColumnTitlePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задайте потребители.
        /// </summary>
        public static string AssignUsersLabel {
            get {
                return ResourceManager.GetString("AssignUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Календар.
        /// </summary>
        public static string CalendarButtonText {
            get {
                return ResourceManager.GetString("CalendarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отхвърляне.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можете да премахвате потребител от незапазена задача!.
        /// </summary>
        public static string CannotRemoveUserUnsavedError {
            get {
                return ResourceManager.GetString("CannotRemoveUserUnsavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвят.
        /// </summary>
        public static string ColorModalEditLabelText {
            get {
                return ResourceManager.GetString("ColorModalEditLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение на новата парола.
        /// </summary>
        public static string ConfirmNewPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждаване на парола.
        /// </summary>
        public static string ConfirmPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да премахнете достъпа на този потребител до проекта?.
        /// </summary>
        public static string ConfirmRemoveModalText {
            get {
                return ResourceManager.GetString("ConfirmRemoveModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете премахването.
        /// </summary>
        public static string ConfirmRemoveModalTitle {
            get {
                return ResourceManager.GetString("ConfirmRemoveModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на етикет.
        /// </summary>
        public static string CreateLabelSubmitButtonText {
            get {
                return ResourceManager.GetString("CreateLabelSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задайте му име, описание и цвят.
        /// </summary>
        public static string CreateLabelSubtitleText {
            get {
                return ResourceManager.GetString("CreateLabelSubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов етикет.
        /// </summary>
        public static string CreateLabelTitleText {
            get {
                return ResourceManager.GetString("CreateLabelTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов проект.
        /// </summary>
        public static string CreateNewProjectNavButtonText {
            get {
                return ResourceManager.GetString("CreateNewProjectNavButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на проект.
        /// </summary>
        public static string CreateProjectButtonText {
            get {
                return ResourceManager.GetString("CreateProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задайте му име и описание.
        /// </summary>
        public static string CreateProjectSubtitleText {
            get {
                return ResourceManager.GetString("CreateProjectSubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създайте нов проект.
        /// </summary>
        public static string CreateProjectTitleText {
            get {
                return ResourceManager.GetString("CreateProjectTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребители, добавени в проекта.
        /// </summary>
        public static string CurrentProjectUsersModalText {
            get {
                return ResourceManager.GetString("CurrentProjectUsersModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        public static string DeleteDropdownButtonText {
            get {
                return ResourceManager.GetString("DeleteDropdownButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да изтриете този етикет?.
        /// </summary>
        public static string DeleteLabelModalText {
            get {
                return ResourceManager.GetString("DeleteLabelModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на етикет.
        /// </summary>
        public static string DeleteLabelModalTitle {
            get {
                return ResourceManager.GetString("DeleteLabelModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване.
        /// </summary>
        public static string DeleteModalButtonText {
            get {
                return ResourceManager.GetString("DeleteModalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да изтриете този проект?.
        /// </summary>
        public static string DeleteProjectModalText {
            get {
                return ResourceManager.GetString("DeleteProjectModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на проект.
        /// </summary>
        public static string DeleteProjectModalTitle {
            get {
                return ResourceManager.GetString("DeleteProjectModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на задача.
        /// </summary>
        public static string DeleteTaskModalTitle {
            get {
                return ResourceManager.GetString("DeleteTaskModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да изтриете тази задача?.
        /// </summary>
        public static string DeleteTaskSureModalText {
            get {
                return ResourceManager.GetString("DeleteTaskSureModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string DescriptionModalEditTaskText {
            get {
                return ResourceManager.GetString("DescriptionModalEditTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В процес.
        /// </summary>
        public static string DoingColumnLabel {
            get {
                return ResourceManager.GetString("DoingColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string DoneColumnLabel {
            get {
                return ResourceManager.GetString("DoneColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайна дата.
        /// </summary>
        public static string DueDateModalEditTaskText {
            get {
                return ResourceManager.GetString("DueDateModalEditTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Край.
        /// </summary>
        public static string DueDatePDFText {
            get {
                return ResourceManager.GetString("DueDatePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай.
        /// </summary>
        public static string EditDropdownButtonText {
            get {
                return ResourceManager.GetString("EditDropdownButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът е в невалиден формат.
        /// </summary>
        public static string EmailIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("EmailIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът е задължително поле.
        /// </summary>
        public static string EmailIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл адрес.
        /// </summary>
        public static string EmailPlaceholderText {
            get {
                return ResourceManager.GetString("EmailPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, първо запазете промените преди да добавяте потребители..
        /// </summary>
        public static string ErrorAddingUserToAnUnsavedTask {
            get {
                return ResourceManager.GetString("ErrorAddingUserToAnUnsavedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при зареждането на потребители..
        /// </summary>
        public static string ErrorLoadingUsersErrorMessageText {
            get {
                return ResourceManager.GetString("ErrorLoadingUsersErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при търсенето.
        /// </summary>
        public static string ErrorSearchingUsers {
            get {
                return ResourceManager.GetString("ErrorSearchingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна проблем при обновяването на задачата. Моля, опитайте отново..
        /// </summary>
        public static string ErrorWhileUpdatingTaskMessageText {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingTaskMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При добавянето на потребители възникна проблем..
        /// </summary>
        public static string ErrorWileAddingUsersErrorMessageText {
            get {
                return ResourceManager.GetString("ErrorWileAddingUsersErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавянето на потребители се провали..
        /// </summary>
        public static string FailedToAddUsersErrorText {
            get {
                return ResourceManager.GetString("FailedToAddUsersErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриването на етиката се провали..
        /// </summary>
        public static string FailedToDeleteLabelErrorMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteLabelErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриването на проекта се провали. Моля, опитайте отново..
        /// </summary>
        public static string FailedToDeleteProjectErrorMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteProjectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриването на задачата се провали. Моля, опитайта отнново..
        /// </summary>
        public static string FailedToDeleteTaskErrorMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteTaskErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареждането на потребители се провали..
        /// </summary>
        public static string FailedToLoadUsersErrorMessageText {
            get {
                return ResourceManager.GetString("FailedToLoadUsersErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахването на потребител беше неуспешно..
        /// </summary>
        public static string FailedToRemoveUserFromProjectErrorMessageText {
            get {
                return ResourceManager.GetString("FailedToRemoveUserFromProjectErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при премахването на потребителя от задачата..
        /// </summary>
        public static string FailedToRemoveUserFromTaskErrorMessageText {
            get {
                return ResourceManager.GetString("FailedToRemoveUserFromTaskErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновяването на задачата се провали. Моля, опитайте отново..
        /// </summary>
        public static string FailedToUpdateTaskText {
            get {
                return ResourceManager.GetString("FailedToUpdateTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтрирай.
        /// </summary>
        public static string FilterDropdownText {
            get {
                return ResourceManager.GetString("FilterDropdownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола?.
        /// </summary>
        public static string ForgotPasswordLinkText {
            get {
                return ResourceManager.GetString("ForgotPasswordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата заявка беше успешна. Моля проверете имейл адреса си за линк за промяна на парола..
        /// </summary>
        public static string ForgotPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генериран.
        /// </summary>
        public static string GeneratedPDFTitleText {
            get {
                return ResourceManager.GetString("GeneratedPDFTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доклад за напредъка.
        /// </summary>
        public static string GenerateReportButtonText {
            get {
                return ResourceManager.GetString("GenerateReportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Започни.
        /// </summary>
        public static string GetStratedButtonLandingText {
            get {
                return ResourceManager.GetString("GetStratedButtonLandingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече имаш акаунт?.
        /// </summary>
        public static string HaveAccountText {
            get {
                return ResourceManager.GetString("HaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Висок.
        /// </summary>
        public static string HighTitlePDFText {
            get {
                return ResourceManager.GetString("HighTitlePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string HomeNavButtonText {
            get {
                return ResourceManager.GetString("HomeNavButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът или паролата не съвпадат.
        /// </summary>
        public static string InvalidLoginErrorMessage {
            get {
                return ResourceManager.GetString("InvalidLoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спомних си паролата.
        /// </summary>
        public static string IRememberedMyPasswordLinkText {
            get {
                return ResourceManager.GetString("IRememberedMyPasswordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to е вече добавен в този проект..
        /// </summary>
        public static string IsAlreadyAddedToTheProject {
            get {
                return ResourceManager.GetString("IsAlreadyAddedToTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to е вече зададен..
        /// </summary>
        public static string IsAlreadyAssignedText {
            get {
                return ResourceManager.GetString("IsAlreadyAssignedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to е вече избран от Вас..
        /// </summary>
        public static string IsAlreadyInYourSelectionText {
            get {
                return ResourceManager.GetString("IsAlreadyInYourSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави приоритет.
        /// </summary>
        public static string IsPriorityCheckLabel {
            get {
                return ResourceManager.GetString("IsPriorityCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to канбан дъска.
        /// </summary>
        public static string KanbanBoardTitleText {
            get {
                return ResourceManager.GetString("KanbanBoardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канбан.
        /// </summary>
        public static string KanbanButtonText {
            get {
                return ResourceManager.GetString("KanbanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етикетът беше изтрит успешно..
        /// </summary>
        public static string LabelSuccessfullyDeletedPopupText {
            get {
                return ResourceManager.GetString("LabelSuccessfullyDeletedPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етикети.
        /// </summary>
        public static string LabelsViewTitle {
            get {
                return ResourceManager.GetString("LabelsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to етикета.
        /// </summary>
        public static string LabelsWordText {
            get {
                return ResourceManager.GetString("LabelsWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличете производителността на екипа си с това интуитивно решение за управление на проекти..
        /// </summary>
        public static string LandingSubtext {
            get {
                return ResourceManager.GetString("LandingSubtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пригответе се да подобрите организацията си.
        /// </summary>
        public static string LandingTitle1 {
            get {
                return ResourceManager.GetString("LandingTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to многократно с AlloK8.
        /// </summary>
        public static string LandingTitle2 {
            get {
                return ResourceManager.GetString("LandingTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарежда....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравей! Нека да започваме.
        /// </summary>
        public static string LoginFormWelcomeMessage {
            get {
                return ResourceManager.GetString("LoginFormWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginLinkText {
            get {
                return ResourceManager.GetString("LoginLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string LogoutButtonText {
            get {
                return ResourceManager.GetString("LogoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да излезете от Вашия профил?.
        /// </summary>
        public static string LogoutModalMessage {
            get {
                return ResourceManager.GetString("LogoutModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход от системата.
        /// </summary>
        public static string LogoutModalTitle {
            get {
                return ResourceManager.GetString("LogoutModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход от профила.
        /// </summary>
        public static string LogoutNavButtonText {
            get {
                return ResourceManager.GetString("LogoutNavButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов етикет.
        /// </summary>
        public static string NewLabelButtonText {
            get {
                return ResourceManager.GetString("NewLabelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова парола.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямаш профил?.
        /// </summary>
        public static string NoAccountText {
            get {
                return ResourceManager.GetString("NoAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормален.
        /// </summary>
        public static string NormalTitlePDFText {
            get {
                return ResourceManager.GetString("NormalTitlePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма зададени потребители.
        /// </summary>
        public static string NoUsersAssignedText {
            get {
                return ResourceManager.GetString("NoUsersAssignedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не бяха намерени потребители..
        /// </summary>
        public static string NoUsersFoundMessageText {
            get {
                return ResourceManager.GetString("NoUsersFoundMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все още няма потребители в този проект.ъ.
        /// </summary>
        public static string NoUsersInThisProjectYetMessageText {
            get {
                return ResourceManager.GetString("NoUsersInThisProjectYetMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string OfPDFText {
            get {
                return ResourceManager.GetString("OfPDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стара парола.
        /// </summary>
        public static string OldPasswordLabel {
            get {
                return ResourceManager.GetString("OldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Само моите.
        /// </summary>
        public static string OnlyMineButtonText {
            get {
                return ResourceManager.GetString("OnlyMineButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница.
        /// </summary>
        public static string PagePDFText {
            get {
                return ResourceManager.GetString("PagePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдената парола не съвпада.
        /// </summary>
        public static string PasswordIsDifferentThanConfirmedErrorMessage {
            get {
                return ResourceManager.GetString("PasswordIsDifferentThanConfirmedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължително поле.
        /// </summary>
        public static string PasswordIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string PasswordPlaceholderText {
            get {
                return ResourceManager.GetString("PasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да съдържа малка буква.
        /// </summary>
        public static string PasswordRequiresLowerErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresLowerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да съдържа символ.
        /// </summary>
        public static string PasswordRequiresNonAlphanumericErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да съдържа голяма буква.
        /// </summary>
        public static string PasswordRequiresUpperErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresUpperErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата трябва да е поне 6 символа.
        /// </summary>
        public static string PasswordTooShortErrorMessage {
            get {
                return ResourceManager.GetString("PasswordTooShortErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете поне един потребител!.
        /// </summary>
        public static string PleaseSelectAtLeastOneUserText {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, изберете поне един потребител за добавяне..
        /// </summary>
        public static string PleaseSelectUserToAddMessageText {
            get {
                return ResourceManager.GetString("PleaseSelectUserToAddMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритет.
        /// </summary>
        public static string PriorityColumnTitlePDFText {
            get {
                return ResourceManager.GetString("PriorityColumnTitlePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогрес.
        /// </summary>
        public static string ProgressColumnTitlePDFText {
            get {
                return ResourceManager.GetString("ProgressColumnTitlePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на проекта.
        /// </summary>
        public static string ProjectNameLabelText {
            get {
                return ResourceManager.GetString("ProjectNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string ProjectPDFTitleText {
            get {
                return ResourceManager.GetString("ProjectPDFTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекти.
        /// </summary>
        public static string ProjectsNavButtonText {
            get {
                return ResourceManager.GetString("ProjectsNavButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проектът беше изтрит успешно..
        /// </summary>
        public static string ProjectSuccessfullyDeletedPopupText {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyDeletedPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterLinkText {
            get {
                return ResourceManager.GetString("RegisterLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата регистрация беше успешна. Използвайте данните си за да влезете в системата..
        /// </summary>
        public static string RegisterSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахване.
        /// </summary>
        public static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доклад за напредъка.
        /// </summary>
        public static string ReportPDFTitleText {
            get {
                return ResourceManager.GetString("ReportPDFTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смени паролата.
        /// </summary>
        public static string ResetPasswordButtonText {
            get {
                return ResourceManager.GetString("ResetPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на парола.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси потребители....
        /// </summary>
        public static string SearchForUsersPlaceholderText {
            get {
                return ResourceManager.GetString("SearchForUsersPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търси потребители.
        /// </summary>
        public static string SearchUsersTitleText {
            get {
                return ResourceManager.GetString("SearchUsersTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избрани потребители за добавяне.
        /// </summary>
        public static string SelectedUsersToAddTitleText {
            get {
                return ResourceManager.GetString("SelectedUsersToAddTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати заявка за промяна на парола.
        /// </summary>
        public static string SendResetRequestButtonText {
            get {
                return ResourceManager.GetString("SendResetRequestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сподели.
        /// </summary>
        public static string ShareDropdownButtonText {
            get {
                return ResourceManager.GetString("ShareDropdownButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сподели проекта.
        /// </summary>
        public static string ShareProjectModalTitleText {
            get {
                return ResourceManager.GetString("ShareProjectModalTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кратко описание.
        /// </summary>
        public static string ShortDescriptionLabelText {
            get {
                return ResourceManager.GetString("ShortDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов си?.
        /// </summary>
        public static string SignUpHeader1Text {
            get {
                return ResourceManager.GetString("SignUpHeader1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрацията е лесна. Отнема само няколко стъпки.
        /// </summary>
        public static string SignUpHeader2Text {
            get {
                return ResourceManager.GetString("SignUpHeader2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По приоритет.
        /// </summary>
        public static string SortByPriorityButtonText {
            get {
                return ResourceManager.GetString("SortByPriorityButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начална дата.
        /// </summary>
        public static string StartDateModalEditTaskText {
            get {
                return ResourceManager.GetString("StartDateModalEditTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string StartDatePDFText {
            get {
                return ResourceManager.GetString("StartDatePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази промените.
        /// </summary>
        public static string SubmitChangesModalEditButtonText {
            get {
                return ResourceManager.GetString("SubmitChangesModalEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string TaskColumnTitlePDFText {
            get {
                return ResourceManager.GetString("TaskColumnTitlePDFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи в проекта.
        /// </summary>
        public static string TasksPDFTitleText {
            get {
                return ResourceManager.GetString("TasksPDFTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачата беше изтрита успешно..
        /// </summary>
        public static string TaskSuccessfullyDeletedPopupText {
            get {
                return ResourceManager.GetString("TaskSuccessfullyDeletedPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачата беше обновена успешно!.
        /// </summary>
        public static string TaskUpdatedSuccessfullyMessageText {
            get {
                return ResourceManager.GetString("TaskUpdatedSuccessfullyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребители, отговорни за задачата:.
        /// </summary>
        public static string TaskUsersLabel {
            get {
                return ResourceManager.GetString("TaskUsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие.
        /// </summary>
        public static string TitleModalEditTaskText {
            get {
                return ResourceManager.GetString("TitleModalEditTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string ToDoColumnLabel {
            get {
                return ResourceManager.GetString("ToDoColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждаване смяна на паролата.
        /// </summary>
        public static string UpdateAccountDetailsButtonText {
            get {
                return ResourceManager.GetString("UpdateAccountDetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменете паролата си.
        /// </summary>
        public static string UpdateAccountPasswordText {
            get {
                return ResourceManager.GetString("UpdateAccountPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят вече е добавен в проекта.
        /// </summary>
        public static string UserAlreadyInProjectTitleText {
            get {
                return ResourceManager.GetString("UserAlreadyInProjectTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът Ви е временно заключен.
        /// </summary>
        public static string UserLockedOutErrorMessage {
            get {
                return ResourceManager.GetString("UserLockedOutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят беше премахнат успешно..
        /// </summary>
        public static string UserRemovedSuccessfullyMessageText {
            get {
                return ResourceManager.GetString("UserRemovedSuccessfullyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителите бяха добавени успешно!.
        /// </summary>
        public static string UsersAddedSuccessfullyMessageText {
            get {
                return ResourceManager.GetString("UsersAddedSuccessfullyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят беше премахнат успешно..
        /// </summary>
        public static string UsersRemovedSuccessfullyMessageText {
            get {
                return ResourceManager.GetString("UsersRemovedSuccessfullyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре дошли!.
        /// </summary>
        public static string WelcomeTitleText {
            get {
                return ResourceManager.GetString("WelcomeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашите проекти.
        /// </summary>
        public static string YourProjectsTitleText {
            get {
                return ResourceManager.GetString("YourProjectsTitleText", resourceCulture);
            }
        }
    }
}
